## *************************** ## 
##        start plugin         ##
## *************************** ##

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'Daiki48/coolnessFlair.vim'
rev = 'develop'
hook_add = '''
colorscheme coolnessFlair
'''

# [[plugins]]
# repo = 'ellisonleao/gruvbox.nvim'
# lua_add = '''
# require('color_scheme.gruvbox')
# '''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
depends = ['nvim-tree/nvim-web-devicons']
lua_add = '''require('modules.lualine')'''

[[plugins]]
repo = 'terrortylor/nvim-comment'
lua_add = '''require('modules.nvim-comment')'''

[[plugins]]
repo = 'williamboman/mason.nvim'
lua_add = '''require('modules.mason')'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_source = 'williamboman/mason.nvim'

# [[plugins]]
# repo = 'vim-denops/denops.vim'
